# Generated by Django 4.1.2 on 2022-10-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='description_en',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='description_ru',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='description_uz',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
