# Generated by Django 4.1.2 on 2022-10-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_menu', '0002_alter_menumodel_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.CharField(max_length=255)),
            ],
        ),
    ]
